insert into public.articles
  (external_id, slug, title, source_name, source_url, category, published_at, keyword, intro, language, status, fetched_at)
values
  (
    'seed-kh-national-20260529-001',
    'korea-herald-national-policy-briefing',
    'National Assembly Debate Puts Youth Policy Back in Focus',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000000',
    'National',
    '2026-05-29T09:00:00.000Z',
    'youth policy',
    'A Korea Herald national story gives learners a compact way to follow policy language, public debate, and the vocabulary of domestic affairs.',
    'en',
    'published',
    now()
  ),
  (
    'seed-kh-business-20260529-001',
    'korea-herald-business-export-outlook',
    'Korean Exporters Watch Currency Moves Ahead of Summer Orders',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000001',
    'Business',
    '2026-05-29T10:20:00.000Z',
    'export outlook',
    'A business item frames market pressure through practical terms around exports, currency movement, demand, and corporate planning.',
    'en',
    'published',
    now()
  ),
  (
    'seed-kh-life-culture-20260529-001',
    'korea-herald-life-culture-museum-night',
    'Museums Extend Evening Hours as Cultural Districts Draw Crowds',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000002',
    'Life&Culture',
    '2026-05-29T11:10:00.000Z',
    'cultural district',
    'A life and culture story is useful for learning descriptive language about public spaces, exhibitions, routines, and city life.',
    'en',
    'published',
    now()
  ),
  (
    'seed-kh-sports-20260529-001',
    'korea-herald-sports-baseball-weekend',
    'Weekend Baseball Series Highlights New Rivalry Momentum',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000003',
    'Sports',
    '2026-05-29T12:30:00.000Z',
    'rivalry momentum',
    'A sports article helps learners read action-oriented reporting, short quotes, rankings, performance, and fan reactions.',
    'en',
    'published',
    now()
  ),
  (
    'seed-kh-world-20260529-001',
    'korea-herald-world-summit-talks',
    'Regional Summit Talks Turn to Trade Routes and Security',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000004',
    'World',
    '2026-05-29T13:45:00.000Z',
    'regional summit',
    'A world news card introduces diplomatic vocabulary around negotiations, alliances, trade routes, and regional security.',
    'en',
    'published',
    now()
  ),
  (
    'seed-kh-kpop-20260529-001',
    'korea-herald-kpop-tour-record',
    'K-pop Group Adds Encore Dates After Global Tour Sellout',
    'The Korea Herald',
    'https://www.koreaherald.com/view.php?ud=20260529000005',
    'K-pop',
    '2026-05-29T14:40:00.000Z',
    'global tour',
    'A K-pop story gives learners accessible entertainment language around fandom, tours, agencies, charts, and global audiences.',
    'en',
    'published',
    now()
  )
on conflict (slug) do update set
  external_id = excluded.external_id,
  title = excluded.title,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  category = excluded.category,
  published_at = excluded.published_at,
  keyword = excluded.keyword,
  intro = excluded.intro,
  language = excluded.language,
  status = excluded.status,
  fetched_at = excluded.fetched_at;
